0.10.6

diff --git a/tests/radius-test b/tests/radius-test
--- a/tests/radius-test
+++ b/tests/radius-test
@@ -32,9 +32,10 @@ fi
 CONFIG="radius"
 IMAGE=ocserv-radius-test
 IMAGE_NAME=test_ocserv_radius
+TMP=$IMAGE_NAME.tmp
 . ./docker-common.sh
 
-$DOCKER run -P --privileged=true -p $PORT:$PORT/udp -p $PORT2:$PORT2/udp -p 22 -p $PORT_OCSERV:$PORT_OCSERV/udp --tty=false -d --name test_ocserv_radius $IMAGE
+$DOCKER run -e OCCTL_PAGER=cat -P --privileged=true --tty=false -d --name $IMAGE_NAME $IMAGE
 if test $? != 0;then
 	echo "Cannot run docker image"
 	exit 1
@@ -44,84 +45,76 @@ echo "ocserv image was run"
 #wait for ocserv to server
 sleep 5
 
-IP=`$DOCKER inspect test_ocserv_radius | grep IPAddress | cut -d '"' -f 4`
+IP=`$DOCKER inspect $IMAGE_NAME | grep IPAddress | cut -d '"' -f 4`
 if test -z "$IP";then
 	echo "Detected IP is null!"
 	stop
 fi
 echo "Detected IP: $IP"
 
-printf "test\ntest\n" >pass.tmp
-openconnect $IP:$PORT_OCSERV -u test --passwd-on-stdin -v --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 < pass.tmp &
+if test ! -z "$QUIT_ON_INIT";then
+	exit 0
+fi
+
+$ECHO_E "testuser" >pass-radius$TMP
+$OPENCONNECT $IP:$PORT_OCSERV -u test --passwd-on-stdin -v --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly < pass-radius$TMP
+if test $? = 0;then
+	echo "Authentication with wrong password succeeded!"
+	stop
+fi
+
+$ECHO_E "test" >pass-radius$TMP
+$OPENCONNECT $IP:$PORT_OCSERV -u testuser --passwd-on-stdin -v --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly < pass-radius$TMP
+if test $? = 0;then
+	echo "Authentication with wrong username succeeded!"
+	stop
+fi
+
+echo "Trying with correct password"
+$ECHO_E "test" >pass-radius$TMP
+$OPENCONNECT $IP:$PORT_OCSERV -u test --passwd-on-stdin -v --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 < pass-radius$TMP &
 PID=$!
 
-rm -f pass.tmp
+rm -f pass-radius$TMP
 
 #wait for openconnect
 sleep 5
 
 # The client IP depends on the username so it shouldn't change.
-ping -w 5 192.168.1.1
+ping -w 5 192.168.55.1
 if test $? != 0;then
 	kill $PID
 	echo "Cannot ping ocserv"
 	stop
 fi
 
-ping -w 5 192.168.1.1 -s 1500
+ping -w 5 192.168.55.1 -s 1500
 if test $? != 0;then
 	kill $PID
 	echo "Cannot ping ocserv"
 	stop
 fi
 
-ping6 -w 5 fd91:6d87:7341:db6a::1
+ping6 -w 5 fd91:6d87:7341:dd6b:0:52:190c:be01
 if test $? != 0;then
 	kill $PID
 	echo "Cannot ping the IPv6 of ocserv"
 	stop
 fi
 
-echo "UserKnownHostsFile ./known-hosts.tmp" >config.tmp
-printf "#\!/bin/sh\n" >echo-admin.tmp
-printf "echo yes" >>echo-admin.tmp
-printf "echo root" >>echo-admin.tmp
-printf "\n" >>echo-admin.tmp
-chmod 755 echo-admin.tmp
-export SSH_ASKPASS="./echo-admin.tmp"
-setsid ssh -T -F config.tmp root@192.168.1.1 occtl show user test >out.tmp 2>&1
-cat out.tmp
-
-printf "#\!/bin/sh\n" >echo-admin.tmp
-printf "echo root" >>echo-admin.tmp
-printf "\n" >>echo-admin.tmp
-chmod 755 echo-admin.tmp
-setsid ssh -T -F config.tmp root@192.168.1.1 occtl show user test >out.tmp 2>&1
-cat out.tmp
-rm -f echo-admin.tmp
-rm -f config.tmp
-rm -f known-hosts.tmp
-
-grep "Username" out.tmp
-if test $? != 0;then
-	kill $PID
-	echo "could not find user information"
-	stop
-fi
-
-rm -f out.tmp
+retrieve_user_info test
 
 # There is an issue in nuttcp that makes it crash under docker if
 # /proc/sys/net/ipv4/tcp_adv_win_scale does not exist.
 if test "$FEDORA" = 1;then
-nuttcp -T 10 -t 192.168.1.1
+nuttcp -T 10 -t 192.168.55.1
 if test $? != 0;then
 	kill $PID
 	echo "Cannot send to ocserv"
 	stop
 fi
 
-nuttcp -T 10 -r 192.168.1.1
+nuttcp -T 10 -r 192.168.55.1
 if test $? != 0;then
 	kill $PID
 	echo "Cannot recv from ocserv"
@@ -129,35 +122,112 @@ if test $? != 0;then
 fi
 fi
 
-sleep 2
+echo "Waiting for accounting report"
+sleep 60
 
-kill $PID
+kill -INT $PID
 
 sleep 4
 
-#check whether /tmp/disconnect/ok was created
-rm -f ./not-ok
-$DOCKER cp test_ocserv_radius:/tmp/disconnect/not-ok ./
-if test -f ./not-ok;then
+check_for_file /tmp/disconnect/not-ok
+if test $? = 0;then
+	echo "There was an issue"
+	stop
+fi
+
+FILE=`$DOCKER exec $IMAGE_NAME ls /var/log/radius/radacct/127.0.0.1/`
+
+OCTETS=`$DOCKER exec $IMAGE_NAME cat "/var/log/radius/radacct/127.0.0.1/$FILE"|grep Acct-Input-Octets|tail -1|sed 's/Acct-Input-Octets = //g'`
+if test -z "$OCTETS" || test "$OCTETS" = 0;then
+	$DOCKER exec $IMAGE_NAME cat "/var/log/radius/radacct/127.0.0.1/$FILE"
+	echo "Interim update showed no data!"
+	stop
+fi
+
+check_for_file /tmp/disconnect/ok
+if test $? != 0;then
+	$DOCKER exec $IMAGE_NAME cat "/var/log/radius/radacct/127.0.0.1/$FILE"
 	echo "There was an issue getting stats"
 	stop
 fi
-rm -f ./not-ok
 
 ret=0
 
-rm -f ./tmp-full/ok
-$DOCKER cp test_ocserv_radius:/tmp/disconnect/ok ./tmp-full/
-if ! test -f ./tmp-full/ok;then
-	echo "Don't know if stats were received"
-	ret=77
-else
-	echo -n "stats: "
-	echo `cat ./tmp-full/ok`
-	rm -rf ./tmp-full/
+#wait until sec-mod has cleaned up its entries
+echo "Waiting for disconnection report"
+sleep 10
+DISC=`$DOCKER exec $IMAGE_NAME cat "/var/log/radius/radacct/127.0.0.1/$FILE"|grep "Acct-Terminate-Cause = User-Request"|tail -1`
+if test -z "$DISC";then
+	$DOCKER exec $IMAGE_NAME cat "/var/log/radius/radacct/127.0.0.1/$FILE"
+	echo "No disconnect was detected!"
+	stop
 fi
 
-$DOCKER stop test_ocserv_radius
-$DOCKER rm test_ocserv_radius
+# do the same with a certificate - test radius accounting with certificate auth
+echo "Trying with certificate"
+rm -f out$TMP.pid
+$DOCKER exec $IMAGE_NAME truncate --size=0 /var/log/radius/radacct/127.0.0.1/$FILE
+$OPENCONNECT $IP:$PORT_OCSERV -b --sslkey ./user-key.pem -c ./user-cert.pem --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --pid-file=out$TMP.pid
+
+sleep 10
+
+if test -f out$TMP.pid;then
+	PID=`cat out$TMP.pid`
+else
+	echo "Cannot determine PID of client"
+	stop
+fi	
+
+ping -w 5 192.168.55.1
+if test $? != 0;then
+	kill $PID
+	echo "Cannot ping ocserv"
+	stop
+fi
+
+
+sleep 4
+
+echo "Waiting for accounting report"
+sleep 60
+
+kill -INT $PID
+
+sleep 10
+
+FILE=`$DOCKER exec $IMAGE_NAME ls /var/log/radius/radacct/127.0.0.1/|tail -1`
+$DOCKER exec $IMAGE_NAME cat "/var/log/radius/radacct/127.0.0.1/$FILE" >out$TMP
+cat out$TMP
+OCTETS=`cat out$TMP|grep Acct-Input-Octets|tail -1|sed 's/Acct-Input-Octets = //g'`
+if test -z "$OCTETS" || test "$OCTETS" = 0;then
+	echo "Interim update showed no data!"
+	stop
+fi
+
+DISC=`cat out$TMP|grep "Acct-Status-Type = Start"|tail -1`
+if test -z "$DISC";then
+	cat out$TMP
+	echo "No connect status was detected!"
+	stop
+fi
+
+DISC=`cat out$TMP|grep "Acct-Terminate-Cause = User-Request"|tail -1`
+if test -z "$DISC";then
+	cat out$TMP
+	echo "No disconnect was detected!"
+	stop
+fi
+
+DISC=`cat out$TMP|grep "NAS-IP-Address = 127.0.0.1"|tail -1`
+if test -n "$DISC";then
+	cat out$TMP
+	echo "NAS-IP-Address has invalid value!"
+	stop
+fi
+
+$DOCKER stop $IMAGE_NAME
+$DOCKER rm $IMAGE_NAME
+
+rm -f out$TMP
 
 exit $ret
